In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [35]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [36]:
## Define the vocabulary size
voc_size=10000

In [37]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [38]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5476, 4278, 6000, 1470],
 [5476, 4278, 6000, 8749],
 [5476, 2411, 6000, 2471],
 [97, 688, 5289, 8880, 4879],
 [97, 688, 5289, 8880, 8152],
 [3914, 5476, 7246, 6000, 3557],
 [9214, 7963, 7576, 8880]]

In [39]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [40]:
import numpy as np

In [41]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5476 4278 6000 1470]
 [   0    0    0    0 5476 4278 6000 8749]
 [   0    0    0    0 5476 2411 6000 2471]
 [   0    0    0   97  688 5289 8880 4879]
 [   0    0    0   97  688 5289 8880 8152]
 [   0    0    0 3914 5476 7246 6000 3557]
 [   0    0    0    0 9214 7963 7576 8880]]


In [42]:
## feature representation
dim=10

In [43]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [44]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step


array([[[-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.57050514e-03,  1.68348290e-02, -2.46532448e-02,
         -2.92922184e-03,  4.76997830e-02, -2.55666375e-02,
         -1.36383176e-02,  1.88983195e-02,  1.290731

In [46]:
embedded_docs[0]

array([   0,    0,    0,    0, 5476, 4278, 6000, 1470])

In [47]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[[-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.78181478e-03, -1.74392834e-02, -4.65657972e-02,
          3.97002138e-02, -2.20581051e-02, -6.80857897e-03,
         -1.42600052e-02, -1.46162994e-02, -1.12642273e-02,
         -5.26758283e-03],
        [-7.57050514e-03,  1.68348290e-02, -2.46532448e-02,
         -2.92922184e-03,  4.76997830e-02, -2.55666375e-02,
         -1.36383176e-02,  1.88983195e-02,  1.290731